---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-data-pv
  namespace: quilr
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/quilradmin/quilr-data/neo4j/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-pvc
  namespace: quilr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: neo4j-data-pv
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-plugins-pv
  namespace: quilr
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/quilradmin/quilr-data/neo4j/plugins
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-plugins-pvc
  namespace: quilr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: neo4j-plugins-pv
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-conf-pv
  namespace: quilr
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/quilradmin/quilr-data/neo4j/conf
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-conf-pvc
  namespace: quilr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: neo4j-conf-pv
  storageClassName: manual
